---
version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "00:00"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "00:00"
    groups:
      docker-github-actions:
        patterns:
          - docker/*
      official-github-actions:
        patterns:
          - actions/*

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "00:00"
