---
changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: 💣 Breaking Changes
      labels:
        - breaking change
    - title: 🔔 Deprecation Warnings
      labels:
        - deprecation
    - title: 🚀 Features
      labels:
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 🧪 Tests
      labels:
        - tests
    - title: 📝 Documentation
      labels:
        - documentation
    - title: ⬆️ Dependencies
      labels:
        - dependencies
    - title: 🔨 Maintenance
      labels:
        - chore
    - title: Other Changes
      labels:
        - "*"
