FROM nginx:1.29.1@sha256:d5f28ef21aabddd098f3dbc21fe5b7a7d7a184720bc07da0b6c9b9820e97f25e AS oss

FROM private-registry.nginx.com/nginx-plus/base:r35-debian-bookworm@sha256:9a82ad3f96d58be861257efd621f215d599e226ebedd24d9f3211bdd743c3c27 AS build

# We create an NGINX Plus image based on the official NGINX Plus Dockerfiles (https://gist.github.com/nginx-gists/36e97fc87efb5cf0039978c8e41a34b5) and modify it by:
# This requires us to have the NGINX Plus license certificate and key from the F5 customer portal,
# so we do not want to embed these certificates and keys in the base image. As such, we use
# in intermediate build image, then throw it away, leaving the modules required.

COPY --from=oss /etc/apt/keyrings/nginx-archive-keyring.gpg /etc/apt/keyrings/

# Download your NGINX license certificate and key from the F5 customer portal (https://account.f5.com) and copy it to the build context
RUN <<EOF
    set -eux
    NGINX_GPGKEY_PATH="/etc/apt/keyrings/nginx-archive-keyring.gpg"
    VERSION_CODENAME="$(grep VERSION_CODENAME /etc/os-release | cut -d= -f2)"
    echo "Acquire::https::pkgs.nginx.com::Verify-Peer \"true\";" > /etc/apt/apt.conf.d/90nginx
    echo "Acquire::https::pkgs.nginx.com::Verify-Host \"true\";" >> /etc/apt/apt.conf.d/90nginx
    echo "Acquire::https::pkgs.nginx.com::SslCert     \"/etc/ssl/nginx/nginx-repo.crt\";" >> /etc/apt/apt.conf.d/90nginx
    echo "Acquire::https::pkgs.nginx.com::SslKey      \"/etc/ssl/nginx/nginx-repo.key\";" >> /etc/apt/apt.conf.d/90nginx
    echo "deb [signed-by=$NGINX_GPGKEY_PATH] https://pkgs.nginx.com/plus/debian ${VERSION_CODENAME} nginx-plus\n" > /etc/apt/sources.list.d/nginx-plus.list
EOF

# Setup NGINX Plus apt repository
RUN --mount=type=secret,id=nginx-crt,dst=nginx-repo.crt \
    --mount=type=secret,id=nginx-key,dst=nginx-repo.key \
    set -eux; \
    mkdir --parents /etc/ssl/nginx; \
    cat nginx-repo.crt > /etc/ssl/nginx/nginx-repo.crt; \
    cat nginx-repo.key > /etc/ssl/nginx/nginx-repo.key

# Only update the NGINX Plus repository
RUN apt-get update

# Download the latest release of the XSLT module and its dependencies
RUN <<EOF
  set -eux
  mkdir --parents /var/cache/apt/downloads
  cd /var/cache/apt/downloads/
  apt-get download nginx-plus-module-xslt
EOF

# Install only envsubst from the gettext-base package
RUN <<EOF
    set -eux
    cd /tmp
    apt-get download gettext-base
    dpkg-deb --extract "$(find . -type f -name 'gettext-base*.deb')" .
    cp usr/bin/envsubst /usr/local/bin/
    rm -rf /tmp/*
EOF

FROM private-registry.nginx.com/nginx-plus/base:r35-debian-bookworm@sha256:9a82ad3f96d58be861257efd621f215d599e226ebedd24d9f3211bdd743c3c27

# OSS equivalent version
ENV NGINX_VERSION=1.29.0

# Proxy cache env vars
ENV PROXY_CACHE_MAX_SIZE=10g
ENV PROXY_CACHE_INACTIVE=60m
ENV PROXY_CACHE_SLICE_SIZE=1m
ENV PROXY_CACHE_VALID_OK=1h
ENV PROXY_CACHE_VALID_NOTFOUND=1m
ENV PROXY_CACHE_VALID_FORBIDDEN=30s

# CORS env vars
ENV CORS_ENABLED=0
ENV CORS_ALLOW_PRIVATE_NETWORK_ACCESS=""

# S3 proxy env vars
ENV DIRECTORY_LISTING_PATH_PREFIX=""
ENV STRIP_LEADING_DIRECTORY_PATH=""
ENV PREFIX_LEADING_DIRECTORY_PATH=""

# Copy files from the OSS NGINX Docker container such that the container
# startup is the same.
COPY --from=build /var/cache/apt/downloads/* /var/cache/apt/downloads/
COPY --from=build /usr/local/bin/envsubst /usr/local/bin/

COPY plus/etc/nginx /etc/nginx
COPY common/etc /etc
COPY common/docker-entrypoint.d /docker-entrypoint.d/

# 1. Install the XLST filter module.
# 2. Adding configuration files needed for proxying private S3 buckets.
# 3. Adding a directory for proxied objects to be stored.
# 4. Adding the entrypoint scripts found in the base NGINX OSS Docker image with a modified version that explicitly sets resolvers.
RUN <<EOF
    set -eux
    apt-get update -qq
    apt-get install --no-install-recommends --no-install-suggests -y "$(find /var/cache/apt/downloads -type f -name 'nginx-plus-module-xslt*.deb')"
    apt-get remove --purge --auto-remove -y
    rm -rf /var/cache/apt/downloads /usr/share/doc/ /usr/share/lintian rm -rf /var/lib/apt/lists/*

    cat /etc/nginx/nginx-license.conf >> /etc/nginx/nginx.conf; \
    rm /etc/nginx/nginx-license.conf; \
    mkdir -p /var/cache/nginx/s3_proxy; \
    chown nginx:nginx /var/cache/nginx/s3_proxy; \
    find /docker-entrypoint.d -type f \( -name '*.sh' -or -name '*.envsh' \) -exec chmod -v +x {} \;
EOF
