# Pull from NGINX image that provides the XSLT module and supporting libraries
FROM private-registry.nginx.com/nginx-plus/modules:r37.0-xslt-debian@sha256:0b4c950977bb5670f450c4c5428e9d4e931e12919dd97e72517c6ab8d5d52501 AS xslt

FROM private-registry.nginx.com/nginx-plus/base:r37.0-debian-trixie@sha256:00bdd05087c951211a1bec52c90bd76ddbe82b4b6be7405beaaa605e5b950a3e

# Proxy cache env vars
ENV PROXY_CACHE_MAX_SIZE=10g
ENV PROXY_CACHE_INACTIVE=60m
ENV PROXY_CACHE_SLICE_SIZE=1m
ENV PROXY_CACHE_VALID_OK=1h
ENV PROXY_CACHE_VALID_NOTFOUND=1m
ENV PROXY_CACHE_VALID_FORBIDDEN=30s
ENV PROXY_CACHE_BYPASS_NO_CACHE=false

# CORS env vars
ENV CORS_ENABLED=0
ENV CORS_ALLOW_PRIVATE_NETWORK_ACCESS=""

# S3 proxy env vars
ENV DIRECTORY_LISTING_PATH_PREFIX=""
ENV STRIP_LEADING_DIRECTORY_PATH=""
ENV PREFIX_LEADING_DIRECTORY_PATH=""

# Copy files from the OSS NGINX Docker container such that the container
# startup is the same.
COPY --from=xslt / /

COPY plus/etc/nginx /etc/nginx
COPY common/etc /etc
COPY common/docker-entrypoint.d /docker-entrypoint.d/

RUN <<EOF
    set -eux
    apt-get update -qq
    apt-get install --no-install-recommends --no-install-suggests -y \
      gettext-base libxml2 libxslt1.1
    apt-get remove --purge --auto-remove -y
    rm -rf /usr/share/doc/ /usr/share/lintian /var/lib/apt/lists

    cat /etc/nginx/nginx-license.conf >> /etc/nginx/nginx.conf; \
    rm /etc/nginx/nginx-license.conf; \
    mkdir -p /var/cache/nginx/s3_proxy; \
    chown nginx:nginx /var/cache/nginx/s3_proxy; \
    find /docker-entrypoint.d -type f \( -name '*.sh' -or -name '*.envsh' \) -exec chmod -v +x {} \;
EOF
