# This key value zone caches the full temporary AWS credential object used by
# dynamic credential providers such as IMDS, ECS, IRSA, and EKS Pod Identity.
keyval_zone zone=instance_credential_cache:32k type=string timeout=6h;
keyval 'instance_credential' $instance_credential_json zone=instance_credential_cache;
