#!/usr/bin/env bash

#
#  Copyright 2026 F5, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

# Shared AWS CLI wrapper for the integration test scripts, used as a generic
# S3 client against the test origin (run_integration_tests.sh plus the cache
# sub-tests it invokes).
#
# This file is sourced, never executed; it carries a shebang only because a
# dialect is what shellcheck needs to lint it (make lint globs
# test/integration/*.sh). The origin endpoint and credentials are passed as
# the sourcing arguments:
#
#   . "$(dirname "${BASH_SOURCE[0]}")/s3_client_lib.sh" \
#     "${endpoint}" "${access_key}" "${secret_key}"
#
# The wrapper lives here rather than as a copy per script because the
# isolation env list below is a security contract that must not drift
# between copies (GH-593 precedent for sourced test helpers).

s3_client_endpoint=$1
s3_client_access_key=$2
s3_client_secret_key=$3

if [ -z "${s3_client_endpoint}" ] || [ -z "${s3_client_access_key}" ] || \
   [ -z "${s3_client_secret_key}" ]; then
  >&2 echo "missing sourcing parameter(s): endpoint URL, access key and secret key for the S3 origin"
  exit 3  # the sourcing scripts' no_dep_exit_code
fi

aws_cmd="$(command -v aws || true)"
if ! [ -x "${aws_cmd}" ]; then
  >&2 echo "required dependency not found: aws (the AWS CLI, used as the S3 test client) not found in the path or not executable"
  exit 3  # the sourcing scripts' no_dep_exit_code
fi

# Prints which AWS CLI binary the suite resolved. A function rather than a
# sourcer-read variable: shellcheck's SC2154 fails `make lint` for a variable
# a script references but never assigns (see entrypoint_test_lib.sh).
s3_client_announce() {
  >&2 echo "Using AWS CLI (S3 test client): ${aws_cmd}"
}

# Re-points the client at another origin endpoint, e.g. when
# run_integration_tests.sh flips the origin between HTTP and HTTPS.
# s3_client_set_endpoint <endpoint url>
s3_client_set_endpoint() {
  s3_client_endpoint="$1"
}

# Runs the AWS CLI as a generic S3 client against the test origin. Every
# invocation is isolated from operator AWS state - ~/.aws config/credentials,
# exported profiles, session tokens and the CLI's interactive auto-prompt are
# all bypassed (env vars reach the CLI even with AWS_CONFIG_FILE nulled, and
# AWS_CLI_AUTO_PROMPT=on would otherwise hang the suite on its prompt UI) -
# so real credentials can never reach the test origin and a local profile
# cannot repoint the client: the same isolation the runner's compose_*
# wrappers apply with env -u. The checksum knobs are pinned to when_required
# so neither an operator export nor an AWS CLI default flip (v2.23 turned on
# CRC32 request checksums) can change the upload wire format the pinned
# origin sees. A custom --endpoint-url makes the CLI sign path-style
# requests, which the origin requires because localhost is not in the
# compose file's RUSTFS_SERVER_DOMAINS.
#
# The TLS flag is derived from the endpoint scheme: the HTTPS test origin
# always serves the throwaway self-signed certificate generated by
# generate_tls_test_certs (whose SANs never cover localhost anyway), so
# --no-verify-ssl is unconditionally correct there. It makes the AWS CLI
# print a urllib3 InsecureRequestWarning on stderr per call; harmless.
# origin_client <aws cli args...>
origin_client() {
  local tls_flag=""
  case "${s3_client_endpoint}" in
    https://*) tls_flag="--no-verify-ssl" ;;
  esac
  # ${tls_flag:+...} expands to nothing when the flag is empty, keeping the
  # argument list clean under `set -o nounset`.
  env -u AWS_PROFILE -u AWS_DEFAULT_PROFILE -u AWS_SESSION_TOKEN \
    -u AWS_CLI_AUTO_PROMPT \
    AWS_ACCESS_KEY_ID="${s3_client_access_key}" \
    AWS_SECRET_ACCESS_KEY="${s3_client_secret_key}" \
    AWS_CONFIG_FILE=/dev/null \
    AWS_SHARED_CREDENTIALS_FILE=/dev/null \
    AWS_EC2_METADATA_DISABLED=true \
    AWS_REQUEST_CHECKSUM_CALCULATION=when_required \
    AWS_RESPONSE_CHECKSUM_VALIDATION=when_required \
    AWS_PAGER="" \
    "${aws_cmd}" --endpoint-url "${s3_client_endpoint}" --region us-east-1 \
    ${tls_flag:+"${tls_flag}"} "$@"
}
